package springboot.hibernate.entity;
// Generated Dec 12, 2016 1:49:28 PM by Hibernate Tools 5.1.0.Alpha1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.hibernate.validator.constraints.NotEmpty;

/**
 * Interviewer generated by hbm2java
 */
@Entity
@Table(name = "interviewer", catalog = "interview_2")
public class Interviewer implements java.io.Serializable {

    private Integer interviewerId;
    private String name;
    private String username;
    private String password;
    private String position;
    private String rolename;
    private boolean enable;
    private Set<Interview> interviews = new HashSet<Interview>(0);

    public Interviewer() {
    }

    public Interviewer(String name, String username, String password, String position, String rolename,
                       boolean enable) {
        this.name = name;
        this.username = username;
        this.password = password;
        this.position = position;
        this.rolename = rolename;
        this.enable = enable;
    }

    public Interviewer(String name, String username, String password, String position, String rolename, boolean enable,
                       Set<Interview> interviews) {
        this.name = name;
        this.username = username;
        this.password = password;
        this.position = position;
        this.rolename = rolename;
        this.enable = enable;
        this.interviews = interviews;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "interviewerId", unique = true, nullable = false)
    public Integer getInterviewerId() {
        return this.interviewerId;
    }

    public void setInterviewerId(Integer interviewerId) {
        this.interviewerId = interviewerId;
    }

    @NotEmpty
    @Column(name = "name", nullable = false, length = 30)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @NotEmpty
    @Column(name = "username", nullable = false, length = 12)
    public String getUsername() {
        return this.username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    @NotEmpty
    @Column(name = "password", nullable = false, length = 12)
    public String getPassword() {
        return this.password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    @NotEmpty
    @Column(name = "position", nullable = false, length = 40)
    public String getPosition() {
        return this.position;
    }

    public void setPosition(String position) {
        this.position = position;
    }

    @NotEmpty
    @Column(name = "rolename", nullable = false, length = 30)
    public String getRolename() {
        return this.rolename;
    }

    public void setRolename(String rolename) {
        this.rolename = rolename;
    }

    @Column(name = "enable", nullable = false)
    public boolean isEnable() {
        return this.enable;
    }

    public void setEnable(boolean enable) {
        this.enable = enable;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "interviewer", cascade = CascadeType.ALL)
    public Set<Interview> getInterviews() {
        return this.interviews;
    }

    public void setInterviews(Set<Interview> interviews) {
        this.interviews = interviews;
    }

}
