package springboot.hibernate.entity;
// Generated Dec 12, 2016 1:49:28 PM by Hibernate Tools 5.1.0.Alpha1

import org.hibernate.validator.constraints.NotEmpty;

import javax.persistence.*;
import java.util.HashSet;
import java.util.Set;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name = "role", catalog = "interview_3")
public class Role implements java.io.Serializable {

    private Integer roleId;
    private String roleName;
    private Set<User> users = new HashSet<User>(0);

    public Role() {
    }

    public Role(String roleName) {
        this.roleName = roleName;
    }

    public Role(String roleName, Set<User> users) {
        this.roleName = roleName;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "roleId", unique = true, nullable = false)
    public Integer getRoleId() {
        return this.roleId;
    }

    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    @NotEmpty
    @Column(name = "roleName", nullable = false, length = 30)
    public String getRoleName() {
        return this.roleName;
    }

    public void setRoleName(String roleName) {
            this.roleName = roleName;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "role", cascade = CascadeType.ALL)
    public Set<User> getUsers() {
        return this.users;
    }

    public void setUsers(Set<User> users) {
        this.users = users;
    }
}
