package springboot.hibernate.entity;
// Generated Dec 12, 2016 1:49:28 PM by Hibernate Tools 5.1.0.Alpha1

import java.util.HashSet;
import java.util.List;
import java.util.Set;

import javax.persistence.*;
import javax.validation.constraints.NotNull;

import static javax.persistence.GenerationType.IDENTITY;

import org.hibernate.validator.constraints.NotEmpty;
import org.springframework.security.core.GrantedAuthority;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name = "user", catalog = "interview_3")
public class User implements java.io.Serializable {

    private Integer userId;
    private String name;
    private String username;
    private String password;
    private String position;
    private Integer roleId;
    private Boolean isEnabled;
    private Set<Interview> interviews = new HashSet<Interview>(0);
    private Role role;

    public User() {
    }

    public User(String name, String username, String password, String position, Integer roleId,
                Boolean isEnabled, Role role) {
        this.name = name;
        this.username = username;
        this.password = password;
        this.position = position;
        this.roleId = roleId;
        this.isEnabled = isEnabled;
        this.role = role;
    }

    public User(String name, String username, String password, String position, Integer roleId, Boolean isEnabled,
                Set<Interview> interviews, Role role) {
        this.name = name;
        this.username = username;
        this.password = password;
        this.position = position;
        this.roleId = roleId;
        this.isEnabled = isEnabled;
        this.interviews = interviews;
        this.role = role;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "userId", unique = true, nullable = false)
    public Integer getUserId() {
        return this.userId;
    }

    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    @NotEmpty
    @Column(name = "name", nullable = false, length = 30)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @NotEmpty
    @Column(name = "username", nullable = false, length = 12)
    public String getUsername() {
        return this.username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    @NotEmpty
    @Column(name = "password", nullable = false, length = 12)
    public String getPassword() {
        return this.password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    @NotEmpty
    @Column(name = "position", nullable = false, length = 40)
    public String getPosition() {
        return this.position;
    }

    public void setPosition(String position) {
        this.position = position;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "user", cascade = CascadeType.ALL)
    public Set<Interview> getInterviews() {
        return this.interviews;
    }

    public void setInterviews(Set<Interview> interviews) {
        this.interviews = interviews;
    }

    @Column(name = "isEnabled")
    public Boolean getIsEnabled() {
        return isEnabled;
    }

    public void setIsEnabled(Boolean enabled) {
        isEnabled = enabled;
    }

    @NotNull
    @Column(name = "roleId")
    public Integer getRoleId() {
        return roleId;
    }

    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    @ManyToOne(fetch = FetchType.EAGER)//, cascade = CascadeType.ALL)
    @JoinColumn(name = "roleId", referencedColumnName = "roleId", nullable = false, insertable = false, updatable = false)
    public Role getRole() {
        return role;
    }

    public void setRole(Role role) {
        this.role = role;
    }
}
