package springboot.hibernate.entity;
// Generated Dec 12, 2016 1:49:28 PM by Hibernate Tools 5.1.0.Alpha1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.hibernate.validator.constraints.NotEmpty;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name = "user", catalog = "interview_3")
public class User implements java.io.Serializable {

    private Integer userId;
    private String name;
    private String username;
    private String password;
    private String position;
    private String rolename;
    private Boolean isEnabled;
    private Set<Interview> interviews = new HashSet<Interview>(0);

    public User() {
    }

    public User(String name, String username, String password, String position, String rolename,
                Boolean isEnabled) {
        this.name = name;
        this.username = username;
        this.password = password;
        this.position = position;
        this.rolename = rolename;
        this.isEnabled = isEnabled;
    }

    public User(String name, String username, String password, String position, String rolename, Boolean isEnabled,
                Set<Interview> interviews) {
        this.name = name;
        this.username = username;
        this.password = password;
        this.position = position;
        this.rolename = rolename;
        this.isEnabled = isEnabled;
        this.interviews = interviews;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "userId", unique = true, nullable = false)
    public Integer getUserId() {
        return this.userId;
    }

    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    @NotEmpty
    @Column(name = "name", nullable = false, length = 30)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @NotEmpty
    @Column(name = "username", nullable = false, length = 12)
    public String getUsername() {
        return this.username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    @NotEmpty
    @Column(name = "password", nullable = false, length = 12)
    public String getPassword() {
        return this.password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    @NotEmpty
    @Column(name = "position", nullable = false, length = 40)
    public String getPosition() {
        return this.position;
    }

    public void setPosition(String position) {
        this.position = position;
    }

    @NotEmpty
    @Column(name = "rolename", nullable = false, length = 30)
    public String getRolename() {
        return this.rolename;
    }

    public void setRolename(String rolename) {
        this.rolename = rolename;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "user", cascade = CascadeType.ALL)
    public Set<Interview> getInterviews() {
        return this.interviews;
    }

    public void setInterviews(Set<Interview> interviews) {
        this.interviews = interviews;
    }

    @Column(name = "isEnabled")
    public Boolean getIsEnabled() {
        return isEnabled;
    }

    public void setIsEnabled(Boolean enabled) {
        isEnabled = enabled;
    }
}
